# Generated by Django 2.0.4 on 2018-07-07 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('oa', models.CharField(max_length=1000)),
                ('ob', models.CharField(max_length=1000)),
                ('oc', models.CharField(max_length=1000)),
                ('od', models.CharField(max_length=1000)),
                ('ans', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='queadd',
            name='qid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.Questions'),
        ),
        migrations.AddField(
            model_name='queadd',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
